#!/usr/bin/env bash
# tier: standard
# @pattern patterns/code/gof/template-method.md
# @pattern patterns/code/vernon/anticorruption-layer.md
#
# smoke-expect.sh — anticorruption layer between drive scripts and expect(1).
#
# Callers stay in bash. This lib hides expect's Tcl syntax quirks and
# exposes 5 bash-friendly verbs: drive_start, drive_send, drive_expect,
# drive_capture, drive_end.
#
# Model: batched expect execution (Approach H per real-body pre-mortem).
# drive_start writes an expect script preamble to a queue file.
# drive_send / drive_expect append Tcl statements to the queue.
# drive_end runs the queue via `expect -f`, captures stdout+stderr to a
# log, marks the session CLOSED. drive_capture copies the log to a
# caller-supplied path.
#
# Exit code vocabulary (per DriveScript interface in decompose doc):
#   0    — success
#   10   — expect script bug / no session / EOF during expect
#   11   — expect timeout
#   12   — assertion fail (reserved; unused by lib today)
#   13   — missing prereq (SCRATCH_DIR, SPAWN_CMD, or expect binary)
#   14   — INFRA fail (drive_capture write failed)
#
# Session state file at $SCRATCH_DIR/.smoke-drive-session — sourceable
# shell assignments. Callers can export _SMOKE_EXPECT_SESSION_STATE
# pointing at that file so subsequent verbs find it. drive_start also
# sets + exports the var in the calling shell.
#
# Bash 3.2 portable. No coproc. No declare -A. No FIFOs.

# Re-source guard — safe to source multiple times per session.
if [[ -n "${_SMOKE_EXPECT_LOADED:-}" ]]; then
  return 0 2>/dev/null || exit 0
fi
_SMOKE_EXPECT_LOADED=1

# Constants — versioned per Hyrum's Law fold H1
readonly SMOKE_EXPECT_VERSION="1.0.0"
readonly SMOKE_EXPECT_UNIMPLEMENTED=42

# _smoke_expect_tcl_escape — escape Tcl-double-quote-string special chars.
# Private helper per Saltzer S6 fold. Escapes: \\ $ [ "  in that order.
# ] and { } inside "..." are literal in Tcl.
_smoke_expect_tcl_escape() {
  local text="$1"
  local escaped="${text//\\/\\\\}"
  escaped="${escaped//\$/\\\$}"
  escaped="${escaped//[/\\[}"
  escaped="${escaped//\"/\\\"}"
  printf '%s' "$escaped"
}

# _smoke_expect_load_session — source the current session state file.
# Sets SMOKE_DRIVE_STATE, SMOKE_DRIVE_QUEUE, SMOKE_DRIVE_LOG, SMOKE_DRIVE_SCRATCH.
# Returns 0 on success, 10 on missing/invalid.
_smoke_expect_load_session() {
  local state_file="${_SMOKE_EXPECT_SESSION_STATE:-}"
  if [ -z "$state_file" ] || [ ! -f "$state_file" ]; then
    return 10
  fi
  # shellcheck source=/dev/null
  . "$state_file" || return 10
  return 0
}

# drive_start — initialize a drive session against a scratch directory.
# Arguments:
#   $1 — SCRATCH_DIR (absolute path; must exist)
#   $2 — SPAWN_CMD (command to spawn as the interactive process)
#   $3.. — SPAWN_ARGS (optional args to SPAWN_CMD)
# Postconditions (per Hoare H2 fold):
#   Queue file at $SCRATCH_DIR/.smoke-drive-queue.exp opens with expect preamble
#   Log file at $SCRATCH_DIR/drive.log created empty
#   Session state file at $SCRATCH_DIR/.smoke-drive-session marks state OPEN
#   _SMOKE_EXPECT_SESSION_STATE exported to the state file path
# Returns:
#   0 on success; 13 on missing/invalid prereqs
drive_start() {
  local scratch_dir="${1:-}"
  local spawn_cmd="${2:-}"

  # S2 fold: precondition checks
  if [ -z "$scratch_dir" ]; then
    echo "smoke-expect: drive_start — SCRATCH_DIR required" >&2
    return 13
  fi
  if [ ! -d "$scratch_dir" ]; then
    echo "smoke-expect: drive_start — SCRATCH_DIR not a directory: $scratch_dir" >&2
    return 13
  fi
  if [ -z "$spawn_cmd" ]; then
    echo "smoke-expect: drive_start — SPAWN_CMD required" >&2
    return 13
  fi
  # S4 fold: expect binary check (graceful missing)
  if ! command -v expect >/dev/null 2>&1; then
    echo "smoke-expect: drive_start — expect(1) not installed; install with 'apt-get install expect' or 'brew install expect'" >&2
    return 13
  fi

  local state_file="$scratch_dir/.smoke-drive-session"
  local queue_file="$scratch_dir/.smoke-drive-queue.exp"
  local log_file="$scratch_dir/drive.log"

  # Build expect preamble
  {
    printf '#!/usr/bin/env expect\n'
    printf '# Auto-generated by smoke-expect.sh %s\n' "$SMOKE_EXPECT_VERSION"
    printf 'log_user 1\n'
    printf 'set timeout 180\n'
  } > "$queue_file"

  # Escape spawn cmd + each arg for Tcl double-quoted string embedding
  local spawn_cmd_esc
  spawn_cmd_esc=$(_smoke_expect_tcl_escape "$spawn_cmd")
  local args_str=""
  shift 2 2>/dev/null || true
  local arg
  for arg in "$@"; do
    local arg_esc
    arg_esc=$(_smoke_expect_tcl_escape "$arg")
    args_str+=" \"$arg_esc\""
  done
  printf 'spawn -noecho "%s"%s\n' "$spawn_cmd_esc" "$args_str" >> "$queue_file"

  # Empty log
  : > "$log_file"

  # H2 fold: write state file LAST so a preamble-write failure = no state file
  {
    printf 'SMOKE_DRIVE_VERSION=%s\n' "$SMOKE_EXPECT_VERSION"
    printf 'SMOKE_DRIVE_SCRATCH=%s\n' "$scratch_dir"
    printf 'SMOKE_DRIVE_QUEUE=%s\n' "$queue_file"
    printf 'SMOKE_DRIVE_LOG=%s\n' "$log_file"
    printf 'SMOKE_DRIVE_STATE=OPEN\n'
  } > "$state_file"

  # Convenience: set + export so bare bash chains don't need an extra export
  _SMOKE_EXPECT_SESSION_STATE="$state_file"
  export _SMOKE_EXPECT_SESSION_STATE
  return 0
}

# drive_send — append a send statement to the queue.
# Arguments:
#   $1 — TEXT (any bash string; escaped for Tcl before embedding)
# Postcondition:
#   send -- "TEXT\n" line appended to the queue file
# Returns:
#   0 on success; 10 on no session
drive_send() {
  local text="${1:-}"
  local rc
  _smoke_expect_load_session; rc=$?
  if [ $rc -ne 0 ]; then
    echo "smoke-expect: drive_send — no session (set _SMOKE_EXPECT_SESSION_STATE or call drive_start first)" >&2
    return 10
  fi
  if [ "${SMOKE_DRIVE_STATE:-}" != "OPEN" ]; then
    echo "smoke-expect: drive_send — session not OPEN (state=${SMOKE_DRIVE_STATE:-unknown})" >&2
    return 10
  fi
  local text_esc
  text_esc=$(_smoke_expect_tcl_escape "$text")
  printf 'send -- "%s\\n"\n' "$text_esc" >> "$SMOKE_DRIVE_QUEUE"
  return 0
}

# drive_expect — append an expect block to the queue.
# Arguments:
#   $1 — PATTERN (Tcl regex; escaped for embedding)
#   $2 — TIMEOUT seconds (default 180 per Feathers F2 fold)
# Postcondition:
#   set timeout + expect { -re PATTERN {} timeout {exit 11} eof {exit 10} } appended
# Returns:
#   0 on queue append success; 10 on no session
drive_expect() {
  local pattern="${1:-}"
  local timeout="${2:-180}"
  local rc
  _smoke_expect_load_session; rc=$?
  if [ $rc -ne 0 ]; then
    echo "smoke-expect: drive_expect — no session" >&2
    return 10
  fi
  if [ "${SMOKE_DRIVE_STATE:-}" != "OPEN" ]; then
    echo "smoke-expect: drive_expect — session not OPEN" >&2
    return 10
  fi
  local pattern_esc
  pattern_esc=$(_smoke_expect_tcl_escape "$pattern")
  {
    printf 'set timeout %s\n' "$timeout"
    printf 'expect {\n'
    printf '  -re "%s" { }\n' "$pattern_esc"
    printf '  timeout { puts stderr "SMOKE_EXPECT_TIMEOUT: %s"; exit 11 }\n' "$pattern_esc"
    printf '  eof { puts stderr "SMOKE_EXPECT_EOF: %s"; exit 10 }\n' "$pattern_esc"
    printf '}\n'
  } >> "$SMOKE_DRIVE_QUEUE"
  return 0
}

# drive_end — run the queued expect script and mark session CLOSED.
# Idempotent per Ousterhout O3 + Hoare H4 folds — no-op when no session
# or already closed.
# Postcondition:
#   expect subprocess terminated (via `expect eof` in the queue)
#   SMOKE_DRIVE_LOG contains stdout+stderr from the expect run
#   Session state file updated to SMOKE_DRIVE_STATE=CLOSED
# Returns:
#   0 on all-expects-matched; 11 on timeout; 10 on expect bug/EOF-before-match
drive_end() {
  local state_file="${_SMOKE_EXPECT_SESSION_STATE:-}"
  if [ -z "$state_file" ] || [ ! -f "$state_file" ]; then
    # Idempotent: no session
    return 0
  fi
  local rc
  _smoke_expect_load_session; rc=$?
  if [ $rc -ne 0 ]; then
    return 0
  fi
  if [ "${SMOKE_DRIVE_STATE:-}" = "CLOSED" ]; then
    return 0
  fi

  # Finish the expect script: close pty (child sees EOF on stdin),
  # reap child, exit 0. `expect eof` after `close` fails because the
  # spawn id is already closed; `wait` is the correct pairing.
  {
    printf 'catch { close }\n'
    printf 'catch { wait }\n'
    printf 'exit 0\n'
  } >> "$SMOKE_DRIVE_QUEUE"

  # Run expect; capture stdout+stderr to log
  local exit_code=0
  expect -f "$SMOKE_DRIVE_QUEUE" > "$SMOKE_DRIVE_LOG" 2>&1 || exit_code=$?

  # Mark state CLOSED (in-place edit; bash 3.2 safe)
  local tmp="$state_file.tmp"
  awk 'BEGIN{FS=OFS="="} /^SMOKE_DRIVE_STATE=/{print "SMOKE_DRIVE_STATE","CLOSED"; next} {print}' \
    "$state_file" > "$tmp" && mv "$tmp" "$state_file"

  # Map expect exit codes to our vocabulary
  case $exit_code in
    0)  return 0  ;;
    10) return 10 ;;
    11) return 11 ;;
    *)  return "$exit_code" ;;
  esac
}

# drive_capture — copy the drive log to a caller-supplied destination.
# Arguments:
#   $1 — DEST_FILE (absolute path; parent dir must exist + be writable)
# Returns:
#   0 on success; 10 on no session; 14 on write failure
drive_capture() {
  local dest="${1:-}"
  local rc
  _smoke_expect_load_session; rc=$?
  if [ $rc -ne 0 ]; then
    echo "smoke-expect: drive_capture — no session" >&2
    return 10
  fi
  if [ -z "$dest" ]; then
    echo "smoke-expect: drive_capture — DEST_FILE required" >&2
    return 14
  fi
  if ! cp "$SMOKE_DRIVE_LOG" "$dest" 2>/dev/null; then
    echo "smoke-expect: drive_capture — write failed to $dest" >&2
    return 14
  fi
  return 0
}

# smoke_expect_version — return the current lib version string.
smoke_expect_version() {
  echo "$SMOKE_EXPECT_VERSION"
}
